Default: &defaults
  database: jijo-kissaten.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: jijo-kissaten_test.sqlite3
  <<: *defaults

Staging:
  database: jijo-kissaten_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: jijo-kissaten_production.sqlite3
  poolsize: 100
  <<: *defaults
